language: 'node_js'
node_js: '8'
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - node_modules
install:
  - npm ci
script:
  - npm run test:travis
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
